Update connection.py
Refactor of get_connection() in order to fix the SSL problem when run the restore-backup.py script:

    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)